moved trivy scan to a separate wfl

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -28,54 +28,36 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       test-http-code: ${{ steps.test-container.outputs.HTTP_CODE }}
-    permissions:
-      security-events: write
 
     steps:
-    - name: Setup Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      - name: Setup Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Build docker image
-      uses: docker/build-push-action@v6
-      with:
-        load: true
-        tags: ${{ env.BASE_TAG }}:latest
-        cache-from: type=gha
-        cache-to: type=gha,mode=max
+      - name: Build docker image
+        uses: docker/build-push-action@v6
+        with:
+          load: true
+          tags: ${{ env.BASE_TAG }}:latest
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
 
-    - name: Run Trivy vulnerability scanner
-      uses: aquasecurity/trivy-action@0.24.0
-      with:
-        image-ref: ${{ env.BASE_TAG }}:latest
-        format: sarif
-        severity: CRITICAL,HIGH
-        exit-code: 1
-        output: trivy-results.sarif
+      - name: Test container
+        id: test-container
+        run: |
+          docker run -d --rm -p 5000:8080 ${{ env.BASE_TAG }}:latest
 
-    - name: Upload Trivy scan results to GitHub Security
-      uses: github/codeql-action/upload-sarif@v3
-      # if: github.ref == 'refs/heads/master'
-      if: always()
-      with:
-        sarif_file: trivy-results.sarif
+          echo "Taking a short nap..."
+          sleep 5s
 
-    - name: Test container
-      id: test-container
-      run: |
-        docker run -d --rm -p 5000:8080 ${{ env.BASE_TAG }}:latest
+          echo "Checking health check endpoint..."
+          curl -Is http://localhost:5000/healthz/ready | head -n 1
+          HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000/healthz/ready)
+          echo "HTTP_CODE=$HTTP_CODE" >> $GITHUB_OUTPUT
 
-        echo "Taking a short nap..."
-        sleep 5s
-
-        echo "Checking health check endpoint..."
-        curl -Is http://localhost:5000/healthz/ready | head -n 1
-        HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000/healthz/ready)
-        echo "HTTP_CODE=$HTTP_CODE" >> $GITHUB_OUTPUT
-
-        echo "Validating response..."
-        if [ "$HTTP_CODE" = "200" ]; then
-          echo "All is valid!"
-        else
-          echo "Response is invalid!"
-          exit 1
-        fi
+          echo "Validating response..."
+          if [ "$HTTP_CODE" = "200" ]; then
+            echo "All is valid!"
+          else
+            echo "Response is invalid!"
+            exit 1
+          fi
diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -34,72 +34,72 @@ jobs:
       contains(inputs.version, 'preview'))
 
     steps:
-    - name: Status check
-      run: |
-        echo "Checking HTTP status..."
-        if [ "${{ needs.build-and-test.outputs.test-http-code }}" = "200" ]; then
-          echo "All is fine, let's push and publish a new version!"
-        else
-          echo "Status is invalid! Abort..."
-          exit 1
-        fi
+      - name: Status check
+        run: |
+          echo "Checking HTTP status..."
+          if [ "${{ needs.build-and-test.outputs.test-http-code }}" = "200" ]; then
+            echo "All is fine, let's push and publish a new version!"
+          else
+            echo "Status is invalid! Abort..."
+            exit 1
+          fi
 
-    - name: Grab a version
-      run: |
-        date=$(date --rfc-3339=date)
-        echo "DATE=${date}" >> $GITHUB_ENV
+      - name: Grab a version
+        run: |
+          date=$(date --rfc-3339=date)
+          echo "DATE=${date}" >> $GITHUB_ENV
 
-        version="${{ github.event_name == 'release' && github.ref || format('{0}.', inputs.version) }}"
-        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
-          version="${version}${date}"
-        fi
-        version="${version/refs\/tags\/v/}"
+          version="${{ github.event_name == 'release' && github.ref || format('{0}.', inputs.version) }}"
+          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+            version="${version}${date}"
+          fi
+          version="${version/refs\/tags\/v/}"
 
-        echo "Version: ${version}"
-        echo "### Version ${version} published! :rocket:" >> $GITHUB_STEP_SUMMARY
-        echo "VERSION=${version}" >> $GITHUB_ENV
+          echo "Version: ${version}"
+          echo "### Version ${version} published! :rocket:" >> $GITHUB_STEP_SUMMARY
+          echo "VERSION=${version}" >> $GITHUB_ENV
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Docker meta
-      id: meta
-      uses: docker/metadata-action@v5
-      with:
-        labels: |
-          org.opencontainers.image.source=${{ github.repositoryUrl }}
-          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
-          org.opencontainers.image.version=${{ env.VERSION }}
-          org.opencontainers.image.revision=${{ github.sha }}
-          org.opencontainers.image.created=${{ env.DATE }}
+      - name: Docker meta
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          labels: |
+            org.opencontainers.image.source=${{ github.repositoryUrl }}
+            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
+            org.opencontainers.image.version=${{ env.VERSION }}
+            org.opencontainers.image.revision=${{ github.sha }}
+            org.opencontainers.image.created=${{ env.DATE }}
 
-    - name: Login to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    - name: Login to GitHub Container Registry
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ github.repository_owner }}
-        password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Build and push
-      uses: docker/build-push-action@v6
-      with:
-        push: true
-        provenance: mode=max
-        sbom: true
-        cache-from: type=gha
-        cache-to: type=gha,mode=max
-        build-args: |
-          VERSION=${{ env.VERSION }}
-          SHA=${{ github.sha }}
-        labels: ${{ steps.meta.outputs.labels }}
-        tags: |
-          ${{ env.BASE_TAG }}:${{ env.VERSION }}
-          ${{ env.BASE_TAG }}:latest
-          ghcr.io/${{ env.BASE_TAG }}:${{ env.VERSION }}
-          ghcr.io/${{ env.BASE_TAG }}:latest
+      - name: Build and push
+        uses: docker/build-push-action@v6
+        with:
+          push: true
+          provenance: mode=max
+          sbom: true
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          build-args: |
+            VERSION=${{ env.VERSION }}
+            SHA=${{ github.sha }}
+          labels: ${{ steps.meta.outputs.labels }}
+          tags: |
+            ${{ env.BASE_TAG }}:${{ env.VERSION }}
+            ${{ env.BASE_TAG }}:latest
+            ghcr.io/${{ env.BASE_TAG }}:${{ env.VERSION }}
+            ghcr.io/${{ env.BASE_TAG }}:latest
